language: node_js
node_js:
  - "11"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
- ng lint query-params-store
- ng test query-params-store --watch=false --browsers=ChromeHeadless
